In [1]:
#pip install torch torchvision torchaudio

In [2]:
import torch
import numpy as np

### Initializing a Tensor

In [3]:
#Providong data and then converting it into a tensor
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
#Creating a numpy array and then converting it into a tensor
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [5]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data,dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

x_rand = torch.reshape(x_data,(1,4)) # overrides the shape of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3368, 0.8758],
        [0.0295, 0.2527]]) 

Random Tensor: 
 tensor([[1, 2, 3, 4]]) 



**Shape** is a tuple of tensor dimensions. Below we have initialised tensors of constant and random values.

In [6]:
shape = (1,2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[[0.7964, 0.0941, 0.9289],
         [0.1341, 0.1607, 0.2477]]]) 

Ones Tensor: 
 tensor([[[1., 1., 1.],
         [1., 1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0., 0.],
         [0., 0., 0.]]])


### Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [7]:
tensor = torch.rand(3,4)

In [8]:
tensor

tensor([[0.2296, 0.4170, 0.4477, 0.8288],
        [0.0838, 0.2151, 0.8574, 0.8338],
        [0.3723, 0.0572, 0.0054, 0.5657]])

In [9]:
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Operations on Tensors

Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation, sampling and more are comprehensively described here https://pytorch.org/docs/stable/torch.html.

**Standard numpy-like indexing and slicing**

In [10]:
# We can move our tensor to the GPU if available with the below 2 LOC
#if torch.cuda.is_available():
#   tensor = tensor.to("cuda")

tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors**

In [11]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)
#0=-2=vertical and -1=1=horizontal

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Arithmetic operations on tensors**

In [12]:
# This computes the matrix multiplication between two tensors. 
# y1, y2, y3 will have the same value.
# ``tensor.T`` returns the transpose of a tensor

In [13]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [14]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [15]:
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [16]:
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [17]:
y3

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [18]:
# This computes the element-wise product. 
# z1, z2, z3 will have the same value.

In [19]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [20]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [21]:
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [22]:
z2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [23]:
z3

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

**Single element tensors**

In [24]:
print(tensor)
agg=tensor.sum() 
#In the above line we are using the aggregating function sum() to add all the elements of the tensor into a tensor with single element
agg_item=agg.item()
#in the above line we are changing the datatype of the tensor into a pythin numerical value
print(agg_item,type(agg_item))

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
12.0 <class 'float'>


**Inplace operations**

In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

In [25]:
tensor.add_(5) #tried - mul,sub,copy as well
#element wise operation of tensor with the operator and the operand in paranthesis
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


### Bridge with NumPy

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

#### Tensor to NumPy array

In [26]:
t=torch.zeros(7)
#initialising a tensor of zeroes with size 7
print(t)
n=t.numpy()
#converting the tensor into anumpy array
print(n)
t.add_(4)
#adding 4 to each element in the tensor to see if change also occurs in the numpy array
print(t)
print(n)

tensor([0., 0., 0., 0., 0., 0., 0.])
[0. 0. 0. 0. 0. 0. 0.]
tensor([4., 4., 4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4. 4. 4.]


#### NumPy array to Tensor

In [27]:
n = np.ones(5)
#initialising a numpy array of ones with size 5
t = torch.from_numpy(n)
#converting from numpy to tensor
np.add(n, 2, out=n)
#adding 2 to the numpy array n to see for a change in tensor t
print(t)
print(n)

tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
[3. 3. 3. 3. 3.]
